server {
    #listen 9090;
    listen 9099;
    server_name jaws;
    client_body_buffer_size 16k;
    client_max_body_size 4m;

    if ( $time_iso8601 ~ "^(\d{4})-(\d{2})-(\d{2})" ) {
        set $year $1;
        set $month $2;
        set $day $3;
    }

    access_log  /log/middle/nginx/jaws-9090-$year-$month-$day-access.log main;
    error_log  /log/middle/nginx/jaws-9090-error.log  notice;
    

    location / {
       
        limit_except GET POST OPTIONS {
            deny all;
        }
	if ($uri ~ ^/((?!js)(?!img)(?!css)(?!fonts)(?!wasm).)*$) {

            rewrite .* /index.html break;
        }
        root    /opt/jaws/web;
        index   index.html;
    }
}
